### ISSUE TITLE
Sprite pixel colors are off

### ISSUE THREAD

**Issue by Dooskington** [Dooskington/gb-emu#81]
Something's up with the pixels in a sprite. Watch the blocks in Tetris as they fall down. When a block is placed, it is converted to a background tile, and you can see the correct coloring. The problem is that the sprite colors and the tile colors differ slightly, which shouldn't be happening because they use the same tile data. I'm unsure of the exact cause.

**Comment by Dooskington** [comment]
Upon closer examination, it seems like the sprite is drawing an extra, black, line of pixels on the bottom of the sprite ( no matter which way it is rotated ), and the line at the top is either missing or has a wrong color. Still unsure.

**Comment by Dooskington** [comment]
Attached is an example of the bug in action. Look at the sprite that flashes over the "OFF" text. The actual "off" part is right, but the sprite seems to be getting some "extra" pixels at the bottom there.
<img width="320" alt="bug" src="https://cloud.githubusercontent.com/assets/4643504/11279686/f94646ee-8ebf-11e5-95fa-f3793281a6d1.png">

**Comment by TyrenDe** [comment]
![image](https://cloud.githubusercontent.com/assets/7430723/11282127/8f1aa4ac-8eb2-11e5-8f58-f7d47c13d22f.png)

**Comment by TyrenDe** [comment]
I think I have a fix. Our "pixelVal" calc was off.
